# Generated by Django 5.2 on 2025-04-10 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=265, verbose_name='title')),
                ('subtitle', models.CharField(max_length=265, verbose_name='subtitle')),
                ('video', models.FileField(upload_to='videos/%Y/%m', verbose_name='video')),
            ],
            options={
                'verbose_name': 'header',
                'verbose_name_plural': 'header',
                'db_table': 'header',
            },
        ),
    ]
