# Generated by Django 5.2 on 2025-04-10 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='name')),
                ('position', models.CharField(max_length=256, verbose_name='position')),
                ('image', models.ImageField(upload_to='team/%Y/%m', verbose_name='image')),
            ],
            options={
                'verbose_name': 'team member',
                'verbose_name_plural': 'team members',
                'db_table': 'team',
            },
        ),
    ]
