# Generated by Django 5.2 on 2025-04-12 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Introduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='title')),
                ('content', models.CharField(max_length=256, verbose_name='content')),
            ],
            options={
                'verbose_name': 'title',
                'verbose_name_plural': 'title',
                'db_table': 'intro',
            },
        ),
    ]
