# Generated by Django 5.2 on 2025-04-12 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_introimages'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='introimages',
            options={'verbose_name': 'image', 'verbose_name_plural': 'Introimages'},
        ),
    ]
