# Generated by Django 5.2 on 2025-04-12 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_alter_introimages_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='FDS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='title')),
                ('content', models.CharField(max_length=256, verbose_name='content')),
            ],
            options={
                'verbose_name': 'Title',
                'verbose_name_plural': 'Title',
                'db_table': 'Title',
            },
        ),
        migrations.CreateModel(
            name='KPT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=256, verbose_name='phone_number')),
                ('email', models.CharField(max_length=256, verbose_name='email')),
                ('location', models.CharField(max_length=265, verbose_name='location')),
            ],
            options={
                'verbose_name': 'Contacts',
                'verbose_name_plural': 'Contacts',
                'db_table': 'Contacts',
            },
        ),
        migrations.CreateModel(
            name='Socials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=256, verbose_name='content')),
                ('social', models.CharField(max_length=256, verbose_name='social')),
            ],
            options={
                'verbose_name': 'Social',
                'verbose_name_plural': 'Social',
                'db_table': 'Socials',
            },
        ),
    ]
