# Generated by Django 5.2 on 2025-04-12 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_fds_kpt_socials'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='name')),
                ('email', models.CharField(max_length=256, verbose_name='email')),
                ('subject', models.CharField(max_length=256, verbose_name='subject')),
                ('message', models.CharField(max_length=256, verbose_name='message')),
            ],
            options={
                'verbose_name': 'contact',
                'verbose_name_plural': 'contacts',
                'db_table': 'contact',
            },
        ),
        migrations.AlterModelOptions(
            name='fds',
            options={'verbose_name': 'Title', 'verbose_name_plural': 'Content'},
        ),
        migrations.AlterModelTable(
            name='fds',
            table='Content',
        ),
    ]
